#!/bin/bash

set -e

if [[ -f /home/jonathan/Desktop/z1/install/zsh ]]
then
  echo "Existing completion detected."
  rm -f /usr/local/share/zsh/site-functions/_z1
  echo "Removed old completion"
  echo
fi

echo "Installing completion for zsh"
echo "Moving completion file to /usr/local/share/zsh/site-functions/_z1"
cp ./../completion/zsh /usr/local/share/zsh/site-functions/_z1
echo 'Installation successful'
echo
echo 'Type "source ~/.zshrc" and open a new terminal to see the changes.'
